domain: alteman.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://alteman.github.io  # the base hostname and protocol for your site, e.g. http://example.com
#baseurl: /alteman.github.io      # place folder name if the site is served in a subfolder
plugins: 
  - jekyll-octicons
